Staff/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'staff'

urlpatterns = [
    path('', views.UserLogin, name='login'),
    path('dashboard/', views.staffProfile, name='profile'),
    path('account_registration/', views.Register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

hospital_mgt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consultations.urls')),
    path('', include('payments.urls')),
    path('', include('patients.urls')),
    path('', include('Staff.urls')),
    

]

patients/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models
# from . import PatientsConfig
app_name = 'patients'

urlpatterns = [
    path('add/', views.Add_patient, name='add_patient'),
    path('detail/<int:pk>/', views.patient_detail, name='detail'),
    path('list/', views.patient_index, name='patient_lists'),
]

patients/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    id_number = models.CharField(max_length=10,unique=True)
    address = models.CharField(max_length=10)
    age = models.IntegerField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    
    class Meta:
        db_table = 'patients'
        managed = True #flush or sync db
    
    def __str__(self):
        return self.name 

patients/views.py
from django.shortcuts import render, redirect
from patients.models import Patient
from django.db.models import Count
    
# Create your views here.
def patient_index(request):
    patients = Patient.objects.all()
    # patients_weekly = Patient.objects.filter(date__month=month).count()
    context = {
        'patients':patients,
        # 'patients_weekly':patients_weekly,
        }
    return render(request, 'patients/patient_lists.html', context)

def patient_detail(request,pk):
    # patient = Patient.objects.get(pk=pk)
    patients = Patient.objects.count()
    context = {
        # 'patient': patient,
        'patients':patients,
        }
    return render(request,'patients/patient_detail.html', context)


def Add_patient(request):
    if request.method =="POST":
        form =request.POST
        #print(form)
        patient= Patient()
        patient.name = form['name']
        patient.mobile = form['mobile']
        patient.id_number = form['id_number']
        patient.address = form['address']
        patient.age = form['age']
        patient.gender = form['gender']
        #patient.address = form['address']
        patient.save()   #insert in database
        
        #give us a new id of the recorded item
        return redirect ('patients:detail', patient.pk)
    return render(request, 'patients/add_patient.html')

templates/patients/add_patient.html
<!-- #creating a form to add patients -->
{% extends 'base/container_page.html' %}
{% block content %}

        <h3>Add new patient</h3>

        <style>
        .view-box {
          position: relative;
          text-align: center;
          }
        </style>

        <div class="view-box">
          <form action="{% url 'patients:add_patient'%}" method="post" name="frmCustomer">
            {%csrf_token %}
            <div class="fields">
              <label for="name">Name: </label>
              <input id="name" type="text" name="name" values="">
              <br>
              
              <label for="mobile">Mobile: </label>
              <input id="mobile" type="text" name="mobile" values="">
              <br>
              
              <label for="id_number">ID Number: </label>
              <input id="id_number" type="text" name="id_number" values="">
              <br>
              
              <label for="address">Address: </label>
              <input id="address" type="text" name="address" values="">
              <br>
              
              <label for="age">Age: </label>
              <input id="age" type="number" name="age" values="">
              <br>
            
              <label for="pin">Gender: </label>
              <select id="gender" name="gender">
                  <option value="male">Male</option>
                  <option value="female">Female</option>
                
              </select>
              <br>
              <input type ="submit" value="save">
            </div>
          </form>  
        
        </div>
       
        
  

    {% endblock %} 

    

templates/patients/patient_detail.html
{% extends 'base/container_page.html' %}
{% block content %}


        <h2><b>Patient information<b></h2>
<style>
    .view_box {
     text-align: center;   
    }
</style>

    <div class="view-box">
        
        <p>Name : {{ patient.name }}</p>
        <p>ID Number : {{ patient.id_number }}</p>
        <p>Address : {{ patient.address }}</p>

    <p><b>Consultation Information<b></p>
    
        <p>Consultation No: {{Consultation.admission}} </p>
        <p>Consultation Type: {{Consultation.test_types}}</p>
    </div>

{% endblock %}

templates/patients/patient_lists.html
{% extends 'base/container_page.html' %}
{% block content %}

<head>
<title> List of Patients </title>
</head>
<body>
   <h1>patients lists</h1>
   <table>
       <thead>
            <th>
            id
           </th>
           <th>
            name
           </th>
           <th>
               mobile
           </th>
           <th>
            id_number
            </th>
            <th>
                address
            </th>
            <th>
                age
            </th>
            <th>
                gender
            </th>

       </thead>
       <tbody>
       {% for patient in patients %}
        <tr>
            <td><a href="{% url 'patients:detail' patient.id %}"></a>{{patient.id}}
            </td>
            <td>
            {{ patient.name}}
            </td>
            <td>
                {{ patient.mobile}}
            </td>
            <td>
                {{ patient.id_number}}
            </td>
            <td>
                {{ patient.address}}
            </td>
            <td>
                {{ patient.age}}
            </td>
            <td>
                {{ patient.gender}}
            </td>
        
        </tr>
            {% endfor %}
       </tbody>
   </table>
{% endblock %} 