Staff/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'staff'

urlpatterns = [
    path('', views.UserLogin, name='login'),
    path('dashboard/', views.staffProfile, name='profile'),
    path('account_registration/', views.Register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

hospital_mgt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consultations.urls')),
    path('', include('payments.urls')),
    path('', include('patients.urls')),
    path('', include('Staff.urls')),
    

]

Staff/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from .managers import CustomUserManager
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('Email Address'), unique= True)
    username = models.CharField(_('Username'), unique= True, max_length=50)
    staff_id = models.CharField(_('staff_id'), unique= True, max_length=10)
    name = models.CharField(_('name'), blank= True, max_length=50)
    mobile_number = models.CharField(_('Mobile Number'), blank= True, unique= True, max_length=50)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ('email',)
    
    objects = CustomUserManager()
    
    #helper functions
    # eg creating user functions/retrieving user & permissions
    
    def _str_(self):
        return self.email
    
    class Meta:
        verbose_name_plural = 'Users'

Staff/views.py
from django.shortcuts import render, redirect
import templates
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages,auth
from django.contrib.auth import update_session_auth_hash
from .models import CustomUser

# # Create your views here.
def UserLogin(request):
    print('user login request')
    if request.method == "POST":
        form = request.POST
        username = request.POST.get('username')
        password  = request.POST.get('password')
        user = authenticate(username=username,password=password)
     
        if user is not None:
            login(request, user)
            print('logged in')
            return redirect('staff:profile')
        
        else:
            messages.info(request,'Invalid username or Password')
            return redirect('staff:login')
            
    return render(request,"Staff/login.html")


def Register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
    context = {'form':form}
    return render(request,"Staff/register.html",context)
    

def staffProfile(request):
    
    return render(request, 'Staff/dashboard.html')


def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return render(request, "Staff/login.html")

# def password_change(request):
#     if request.method == 'POST':
#         form = PasswordChangeForm(user=request.user, data=request.POST)
#         if form.is_valid():
#             form.save()
#             update_session_auth_hash(request, form.user)
#     else:
#         ...

templates/Staff/dashboard.html
{% extends 'base/container_page.html' %}

{% block content%}

<style>
.block{
    text-align: center;
    border: 2px solid gray;
}
</style>
<div class="block">

<h1>Blackboard</h1>

</div>

{% endblock %} 

templates/Staff/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <title>BS Hospital mgt_sys</title>

  <!-- Custom fonts for this template-->
  <link href="static 'site/bootstrap/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="{% static '/site/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  {% comment %} <link href="css/sb-admin-2.min.css" rel="stylesheet"> {% endcomment %}
  {% comment %} <link href="{% static 'site/bootstrap/login.html' %}" rel="stylesheet"> {% endcomment %}
  <link href="{% static 'site/bootstrap/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">


    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form action="{% url 'staff:login' %}" method="post">
                  {% csrf_token %}
                    <div class="form-group">
                      <input type="text" name="username" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter username...">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                      <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">
                    </a>
                    <hr>
                    <a href="{% url 'staff:register'%}" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Register
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Google
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  {% comment %} <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div> {% endcomment %}
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'site/bootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'site/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
  <!-- Core plugin JavaScript-->
  <script src="{% static 'site/bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
<script src="{% static 'site/bootstrap/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/Staff/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Register</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'site/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'site/bootstrap/css/sb-admin-2.min.css' %}" rel="stylesheet">
   <link href="{% static 'site/bootstrap/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="user">
                <div class="form-group row">
                <form action="{% url 'staff:login' %}" method="post">
                  {% csrf_token %}
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" name="name" class="form-control form-control-user" id="exampleFirstName" placeholder="Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" name="staff_id" class="form-control form-control-user" id="exampleLastName" placeholder="Staff ID">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" name="username" class="form-control form-control-user" id="exampleLastName" placeholder="Username">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" name="mobile_number" class="form-control form-control-user" id="exampleLastName" placeholder="Mobile Number">
                  </div>
                </div>
                <div class="form-group">
                  <inpu type="email" name="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">Email
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" name="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                  </div>
                </div>
                <input type="submit" class="btn btn-primary btn-user btn-block" value="Register Account">

                <hr>
                <a href="{% url 'staff:login' %}" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Already have an account? Login!
                </a>
              </form>
              <hr>
              {% comment %} <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div> {% endcomment %}
              {% comment %} <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
              </div> {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>