Staff/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'staff'

urlpatterns = [
    path('', views.UserLogin, name='login'),
    path('dashboard/', views.staffProfile, name='profile'),
    path('account_registration/', views.Register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

consultations/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'consultations'

urlpatterns = [
    path('make_consultation', views.consult, name='consult'),
    path('consultation_lists', views.Consultation_index, name='consult_lists'),
]

hospital_mgt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consultations.urls')),
    path('', include('payments.urls')),
    path('', include('patients.urls')),
    path('', include('Staff.urls')),
    

]

patients/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models
# from . import PatientsConfig
app_name = 'patients'

urlpatterns = [
    path('add/', views.Add_patient, name='add_patient'),
    path('detail/<int:pk>/', views.patient_detail, name='detail'),
    path('list/', views.patient_index, name='patient_lists'),
]

consultations/models.py
from django.db import models
from patients.models import Patient

# Create your models here.   # patient id, past history, history, test-types, notes, prescriptions
class Consultation(models.Model):
    patient_id = models.ForeignKey(Patient,on_delete=models.CASCADE,default=1)
    medical_history = models.CharField(max_length=100)
    ADMISSION_TYPES = (
        ('Y', 'Yes'),   
        ('N', 'No'),
    )
    admission = models.CharField(max_length=5, choices=ADMISSION_TYPES)
    TEST_TYPES = (
        ('Lab', 'Labaratory'),   
        ('cardio', 'cardiovascular'),
        ('skin', 'dermatology'),
        ('ENT', 'ENT'),
        ('gastro', 'gastrointerstinal'),
        ('blood', 'haematology'),
        ('brain', 'neurological'),
        ('gynae', 'gynaelogical'),
        ('visual', 'ocular'),
        ('joints', 'rheumatology'),
        ('heart', 'pulmonary'),
        ('imaging', 'radiology'),
        ('urine', 'urology'),
    )
    test_types = models.CharField(max_length=20, choices=TEST_TYPES )
    notes = models.CharField(max_length=500)
    prescription = models.CharField(max_length=300)
    

    class Meta:
        db_table = 'consultations'
        managed = True #flush or sync db
    
    def __str__(self):
        return self.test_types

consultations/views.py
from django.shortcuts import render
from django.db.models import Count
from consultations.models import Consultation
from patients.models import Patient

# Create your views here.
def consult(request):
    if request.method =="POST":
        form =request.POST
        consult= Consultation()
        pat_name = Patient()
        pat_name.name = form['patient_id']
        consult.medical_history = form['medical_history']
        consult.admission = form['admission']
        consult.test_types = form['test_types']
        consult.notes = form['notes']
        consult.prescription = form['prescription']
        consult.save()   #insert in database
        
        #give us a new id of the recorded item
        return redirect ('patient:detail', patient.pk)
    return render(request, 'consultations/consult.html')

def Consultation_index(request):
    bed_occupancy = Consultation.objects.filter(admission).count()
    tests = Consultation.objects.filter(test_types)
    pharmacy = Consultation.objects.filter(prescription)
    context = {
        'bed_occupancy':bed_occupancy,
        'tests':tests,
        'prescription':prescription
        }
    return render(request, 'consultations/consult_lists.html', context)

templates/consultations/consult.html
<!-- #creating a form to make a consultation -->
{% extends 'base/container_page.html' %}
{% block content %}
    <style>
        .view-box {
            position: relative;
            text-align: center;
            border: 1px;
        }
    </style>

            
        <div class="view-box">
        <h2>Make a consultation</h2>
            <form action="{% url 'consultations:consult'%}" method="post" name="frmCustomer">
                {%csrf_token %}

                <label for="patient_id">Patient Name: </label>
                <input id="{{pat_name.id}}" type="text" name="patient_id" values="">
                <br>
                <label for="medical_history">Medical_history: </label>
                <input id="medical_history" type="text" name="medical_history" values="">
                <br>
                <label for="admission">Admission: </label>
                <select id="admission" name="admission">
                  <option value="No">No</option>
                  <option value="Yes">Yes</option>
                </select>
                <br>
                <label for="test_types">Test_types: </label>
                <select id="test_types" name="test_types" multiple size="5">
                  <option value="Labaratory">Labaratory</option>
                  <option value="cardiovascular">cardiovascular</option>
                  <option value="dermatology">dermatology</option>
                  <option value="ENT">ENT</option>
                  <option value="gastrointerstinal">gastrointerstinal</option>
                  <option value="haematology">haematology</option>
                  <option value="neurological">neurological</option>
                  <option value="gynaelogical">gynaelogical</option>
                  <option value="ocular">ocular</option>
                  <option value="rheumatology">rheumatology</option>
                  <option value="pulmonary">pulmonary</option>
                  <option value="radiology">radiology</option>
                  <option value="urology">urology</option>
                  <option value="Others">Others</option>
                
              </select>
                <br>
                <label for="notes">Notes: </label>
                <input id="notes type="text" name="notes" values="">
                <br>
                <label for="prescription">Prescription: </label>
                <input id="prescription" type="text" name="prescription" values="">
                <br>
                <input type ="submit" value="save">

            </form>
        </div>


{% endblock %} 

templates/consultations/consult_lists.html
{% extends 'base/container_page.html' %}
{% block content %}

<head>
<title> List of Patients </title>
</head>
<body>
   <h1>patients lists</h1>
   <table>
       <thead>
            <th>
            id
           </th>
           <th>
            Medical history
           </th>
           <th>
            Admission
           </th>
           <th>
            Test_types
            </th>
            <th>
            Notes
            </th>
            <th>
            Prescription
            </th>

       </thead>
       <tbody>
       {% for consultation in consultations %}
        <tr>
            <td><a href="{% url 'consultations:detail' consultation.id %}"></a>{{consultation.id}}
            </td>
            <td>
            {{ consultation.patient_id}}
            </td>
            <td>
                {{ consultation.medical_history}}
            </td>
            <td>
                {{ consultation.admission}}
            </td>
            <td>
                {{ consultation.test_types}}
            </td>
            <td>
                {{ consultation.notes}}
            </td>
            <td>
                {{ consultation.prescription}}
            </td>
        
        </tr>
            {% endfor %}
       </tbody>
   </table>
{% endblock %} 