Staff/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'staff'

urlpatterns = [
    path('', views.UserLogin, name='login'),
    path('dashboard/', views.staffProfile, name='profile'),
    path('account_registration/', views.Register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

hospital_mgt_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consultations.urls')),
    path('', include('payments.urls')),
    path('', include('patients.urls')),
    path('', include('Staff.urls')),
    

]

payments/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import models

app_name = 'payments'

urlpatterns = [
    path('pay/', views.Payment_index, name='make_payment'),
    path('payment_history/', views.Payment_Report, name='payment_list'),
]

payments/models.py
from django.db import models
from patients.models import Patient
from django.utils import timezone

# Create your models here.
class Payment(models.Model):
    time = models.DateTimeField(default=timezone.now)
    patient_id = models.ForeignKey(Patient,on_delete=models.CASCADE,default=1)
    PAYMENT_TYPES = (
        ('Cash', 'Cash'),
        ('Mpesa', 'Mobile_money'),
        ('Insurance', 'Insurance'),
        ('Card', 'Card'),
    )
    payment_type = models.CharField(max_length=9, choices=PAYMENT_TYPES)
    PAYMENT_FOR_OPTIONS = (
        ('Lab', 'Labaratory'),
        ('Con', 'Consultations'), #to include diagnosis and ather specialized services like dental etc
        ('Pharm', 'Pharmacy'),
        ('Ward', 'Admisions'),
        ('All', 'All payments'),
    )
    payment_for = models.CharField(max_length=15, choices=PAYMENT_FOR_OPTIONS)
    amount = models.IntegerField()
    
    
    class Meta:
        db_table = 'payments'
        managed = True #flush or sync db
    
    def __str__(self):
        return self.amount


# patient id, past history, history, test-types, notes, prescriptions

payments/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.daraja.mpesa.core import MpesaClient
from django.urls import reverse
from payments.models import Payment
from patients.models import Patient


# Create your views here.
def Payment_index(request):
    cl = MpesaClient()
    token = cl.access_token
    print(token)
    #use a safaricom phone number you can access
    phone_number = '0727618922'
    amount = 2
    account_reference
    transaction_desc
    callback_url
    response 
    return HttpResponse(response, text)
    # if request.method =="POST":
    #     form =request.POST
    #     #print(form)
    #     payment= Payment()
    #     payment.name = form['time']
    #     payment.mobile = form['patient_id']
    #     payment.id_number = form['payment_type']
    #     payment.address = form['payment_for']
    #     payment.age = form['amount']
        
def stk_push_callback(request):
    data = request.body
    json _data = json.loads(data)
    print(json_data)
    print(json_data['partyB'])
    
    return HttpResponse(data)

    return render(request, 'payments/make_payment.html', context)


        
def Payment_Report(request): 

    patients = Patient.objects.all()

     
    context ={
        'patients':patients,
    }
    return render(request, "payments/payment_history.html",context)
    

templates/payments/make_payment.html
<!-- #creating a form to make payment -->
{% extends 'base/container_page.html' %}
{% block content %}
    <style>
        .view-box {
          position: relative;
          text-align: center;
        }
    </style>

        <h2>Add payment history</h2>
        <div class="view-box">
            <form action="{% url 'customer:add_customer'%}" method="post" name="frmCustomer">
                {%csrf_token %}

                <label for="name">Name: </label>
                <input id="name" type="text" name="name" values="">
                <br>
                <br>
                <label for="mobile">Mobile: </label>
                <input id="mobile" type="text" name="mobile" values="">
                <br>
                <br>
                <label for="id_number">ID Number: </label>
                <input id="id_number" type="text" name="id_number" values="">
                <br>
                <br>
                <label for="balance">Balance: </label>
                <input id="balance" type="number" name="balance" values="">
                <br>
                <br>
                <label for="age">Age: </label>
                <input id="age" type="text" name="age" values="">
                <br>
                <br>
                <label for="pin">Pin: </label>
                <input id="pin" type="text" name="pin" values="">
                <!-- <label for="address">Address: </label>
                <input id="address" type="number" name="address" values="">
                <br>
                <br> -->
                <input type ="submit" value="save">

            </form>
        </div>

    {% endblock %} 

    // URL
[POST] https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest

// HEADERS
Host: sandbox.safaricom.co.ke
Authorization: Bearer [access token]
Content-Type: application/json

// BODY
{
    "BusinessShortCode": "174379",
    "Password": "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTgwNDA5MDkzMDAy",
    "Timestamp": "20180409093002",
    "TransactionType": "[Transaction Type]",
    "Amount": "1000",
    "PartyA": "254708374149",
    "PartyB": "174379",
    "PhoneNumber": "254708374149",
    "CallBackURL": "https://ip:port/"
    "AccountReference": "account",
    "TransactionDesc": "test" ,
}

templates/payments/payment_history.html
{% extends 'base/container_page.html' %}
{% block content %}
    <style>
        .view-box {
          position: relative;
          text-align: center;
        }
    </style>

<title> List of Payments </title>
    
   <h1>Payments made</h1>
   <table>
       <thead>
            <th>
            time
           </th>
           <th>
            patient_id
           </th>
           <th>
               payment_type
           </th>
           <th>
            payment_for
            </th>
            <th>
                amount
            </th>

       </thead>
       <tbody>
       {% for payment in Payments %}
        <tr>
            <td><a href="{% url 'payments:payment_list' payment.id %}"></a>{{payment.id}}
            </td>
            <td>
            {{ payment.time}}
            </td>
            <td>
                {{ payment.patient_id}}
            </td>
            <td>
                {{ payment.payment_type}}
            </td>
            <td>
                {{ payment.payment_for}}
            </td>
            <td>
                {{ payment.amount}}
            </td>
        
        </tr>
            {% endfor %}
       </tbody>
   </table>
 {% endblock %} 
 